CREATE SEQUENCE "USER_ID_SEQ";
CREATE TABLE "USER"
(
    "USER_ID" INTEGER NOT NULL DEFAULT nextval('"USER_ID_SEQ"'),
    "EMAIL" TEXT NOT NULL,
    "PASSWORD_HASH" TEXT NOT NULL,
    "PASSWORD_SALT" TEXT NOT NULL,
    CONSTRAINT "PK_USER" PRIMARY KEY ("USER_ID")
);
INSERT INTO "USER"("EMAIL", "PASSWORD_HASH", "PASSWORD_SALT")
VALUES ('anon', 'NOT-A-HASH', 'NOT-A-SALT');
INSERT INTO "USER"("EMAIL", "PASSWORD_HASH", "PASSWORD_SALT") 
VALUES ('admin', 'b0b6d977c0379ed51918692efb2cd862af898ecb6b64f6a91f03dcea485ffc43', 'c64ffc57-d5fd-434a-9c2d-d284221d60d2');
INSERT INTO "USER"("EMAIL", "PASSWORD_HASH", "PASSWORD_SALT")
VALUES ('testuser', 'b0b6d977c0379ed51918692efb2cd862af898ecb6b64f6a91f03dcea485ffc43', 'c64ffc57-d5fd-434a-9c2d-d284221d60d2');

CREATE SEQUENCE "ACTION_ID_SEQ";
CREATE TABLE "ACTION"
(
    "ACTION_ID" INTEGER NOT NULL DEFAULT nextval('"ACTION_ID_SEQ"'),
    "CODE" TEXT NOT NULL,
    "STAND_SPECIFIC" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_ACTION" PRIMARY KEY ("ACTION_ID")
);
INSERT INTO "ACTION" ("CODE") VALUES ('USER_C');
INSERT INTO "ACTION" ("CODE") VALUES ('USER_R');
INSERT INTO "ACTION" ("CODE") VALUES ('USER_U');
INSERT INTO "ACTION" ("CODE") VALUES ('USER_D');
INSERT INTO "ACTION" ("CODE") VALUES ('STAND_C');
INSERT INTO "ACTION" ("CODE","STAND_SPECIFIC") VALUES ('STAND_R', TRUE);
INSERT INTO "ACTION" ("CODE","STAND_SPECIFIC") VALUES ('STAND_U', TRUE);
INSERT INTO "ACTION" ("CODE","STAND_SPECIFIC") VALUES ('STAND_D', TRUE);
INSERT INTO "ACTION" ("CODE","STAND_SPECIFIC") VALUES ('STAND_OWNER_C', TRUE);
INSERT INTO "ACTION" ("CODE","STAND_SPECIFIC") VALUES ('STAND_OWNER_R', TRUE);
INSERT INTO "ACTION" ("CODE","STAND_SPECIFIC") VALUES ('STAND_OWNER_D', TRUE);

CREATE SEQUENCE "ROLE_ID_SEQ";
CREATE TABLE "ROLE"
(
    "ROLE_ID" INTEGER NOT NULL DEFAULT nextval('"ROLE_ID_SEQ"'),
    "CODE" TEXT NOT NULL,
    "STAND_SPECIFIC" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_ROLE" PRIMARY KEY ("ROLE_ID")
);
INSERT INTO "ROLE"("CODE") VALUES ('GLOBAL_ADMIN');
INSERT INTO "ROLE"("CODE") VALUES ('GLOBAL_STAND_OWNER');
INSERT INTO "ROLE"("CODE") VALUES ('SCOPED_STAND_OWNER');
INSERT INTO "ROLE"("CODE") VALUES ('GLOBAL_ANONYMOUS');

CREATE SEQUENCE "ROLE_ENABLES_ACTION_ID_SEQ";
CREATE TABLE "ROLE_ENABLES_ACTION"
(
    "ROLE_ENABLES_ACTION_ID" INTEGER NOT NULL DEFAULT nextval('"ROLE_ENABLES_ACTION_ID_SEQ"'),
    "ROLE_ID" INTEGER NOT NULL,
    "ACTION_ID" INTEGER NOT NULL,
    CONSTRAINT "PK_ROLE_ENABLES_ACTION" PRIMARY KEY ("ROLE_ENABLES_ACTION_ID"),
    CONSTRAINT "FK_ROLE_ENABLES_ACTION$ACTION" FOREIGN KEY ("ACTION_ID") REFERENCES "ACTION"("ACTION_ID"),
    CONSTRAINT "FK_ROLE_ENABLES_ACTION$ROLE" FOREIGN KEY ("ROLE_ID") REFERENCES "ROLE"("ROLE_ID")
);
INSERT INTO "ROLE_ENABLES_ACTION"("ROLE_ID", "ACTION_ID")
SELECT r."ROLE_ID", a."ACTION_ID" FROM "ROLE" r, "ACTION" a
WHERE r."CODE" = 'GLOBAL_ADMIN'
OR (r."CODE" = 'SCOPED_STAND_OWNER' and a."CODE" in ('STAND_U', 'STAND_D', 'STAND_R', 'STAND_OWNER_C', 'STAND_OWNER_R', 'STAND_OWNER_D'))
OR (r."CODE" = 'GLOBAL_STAND_OWNER' and a."CODE" in ('STAND_C'))
OR (r."CODE" = 'GLOBAL_ANONYMOUS' and a."CODE" in ('STAND_R'));

CREATE SEQUENCE "STAND_ID_SEQ";
CREATE TABLE "STAND"
(
  "STAND_ID" INTEGER NOT NULL DEFAULT nextval('"STAND_ID_SEQ"'),
  "LATITUDE" DOUBLE PRECISION NOT NULL,  
  "LONGITUDE" DOUBLE PRECISION NOT NULL,
  "OPEN_MO" BOOLEAN NOT NULL,  
  "OPEN_TU" BOOLEAN NOT NULL,  
  "OPEN_WE" BOOLEAN NOT NULL,  
  "OPEN_TH" BOOLEAN NOT NULL,  
  "OPEN_FR" BOOLEAN NOT NULL,  
  "OPEN_SA" BOOLEAN NOT NULL,  
  "OPEN_SU" BOOLEAN NOT NULL,
  "EMAIL" TEXT NULL,
  "HOMEPAGE" TEXT NULL,
  "PHONE" TEXT NULL,
  "TITLE" TEXT NULL,
  "SUMMARY" TEXT NULL,
  CONSTRAINT "PK_STAND" PRIMARY KEY ("STAND_ID")
);
INSERT INTO "STAND"("LATITUDE", "LONGITUDE", "OPEN_MO", "OPEN_TU", "OPEN_WE", "OPEN_TH", "OPEN_FR", "OPEN_SA", "OPEN_SU", "EMAIL", "HOMEPAGE", "PHONE", "TITLE", "SUMMARY")
VALUES (1, 1, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 'a@b.c', 'www.a.b', '+41....', 'Demo', 'summary');
INSERT INTO "STAND"("LATITUDE", "LONGITUDE", "OPEN_MO", "OPEN_TU", "OPEN_WE", "OPEN_TH", "OPEN_FR", "OPEN_SA", "OPEN_SU", "EMAIL", "HOMEPAGE", "PHONE", "TITLE", "SUMMARY")
VALUES (1, 1, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 'a@b.c', 'www.a.b', '+41....', 'Demo 2', 'summary 2');

CREATE SEQUENCE "ROLE_ASSIGNMENT_ID_SEQ";
CREATE TABLE "ROLE_ASSIGNMENT"
(
    "ROLE_ASSIGNMENT_ID" INTEGER NOT NULL DEFAULT nextval('"ROLE_ASSIGNMENT_ID_SEQ"'),
    "ROLE_ID" INTEGER NOT NULL,
    "USER_ID" INTEGER NOT NULL,
    "STAND_ID" INTEGER NULL,
    CONSTRAINT "PK_ROLE_ASSIGNMENT" PRIMARY KEY ("ROLE_ASSIGNMENT_ID"),
    CONSTRAINT "FK_ROLE$USER" FOREIGN KEY ("USER_ID") REFERENCES "USER"("USER_ID"),
    CONSTRAINT "FK_ROLE$ROLE" FOREIGN KEY ("ROLE_ID") REFERENCES "ROLE"("ROLE_ID"),
    CONSTRAINT "FK_ROLE$STAND" FOREIGN KEY ("STAND_ID") REFERENCES "STAND"("STAND_ID")
);
INSERT INTO "ROLE_ASSIGNMENT"("ROLE_ID", "USER_ID")
VALUES ((SELECT "ROLE_ID" FROM "ROLE" WHERE "CODE" = 'GLOBAL_ADMIN'), (SELECT "USER_ID" FROM "USER" WHERE "EMAIL" = 'admin'));
INSERT INTO "ROLE_ASSIGNMENT"("ROLE_ID", "USER_ID")
VALUES ((SELECT "ROLE_ID" FROM "ROLE" WHERE "CODE" = 'GLOBAL_ANONYMOUS'), (SELECT "USER_ID" FROM "USER" WHERE "EMAIL" = 'anon'));
INSERT INTO "ROLE_ASSIGNMENT"("ROLE_ID", "USER_ID", "STAND_ID")
VALUES ((SELECT "ROLE_ID" FROM "ROLE" WHERE "CODE" = 'SCOPED_STAND_OWNER'), (SELECT "USER_ID" FROM "USER" WHERE "EMAIL" = 'testuser'), 1);
INSERT INTO "ROLE_ASSIGNMENT"("ROLE_ID", "USER_ID")
VALUES ((SELECT "ROLE_ID" FROM "ROLE" WHERE "CODE" = 'GLOBAL_STAND_OWNER'), (SELECT "USER_ID" FROM "USER" WHERE "EMAIL" = 'testuser'));

SELECT ra."USER_ID", a."CODE" FROM "ROLE_ASSIGNMENT" ra
join "ROLE_ENABLES_ACTION" rea on ra."ROLE_ID" = rea."ROLE_ID"
join "ACTION" A on rea."ACTION_ID" = A."ACTION_ID"
where a."STAND_SPECIFIC" = FALSE;

SELECT ra."USER_ID", a."CODE", s."STAND_ID" FROM "ROLE_ASSIGNMENT" ra
join "ROLE_ENABLES_ACTION" rea on ra."ROLE_ID" = rea."ROLE_ID"
join "ACTION" a on rea."ACTION_ID" = a."ACTION_ID"
join "STAND" s on (s."STAND_ID" = ra."STAND_ID" OR ra."STAND_ID" IS NULL)
where a."STAND_SPECIFIC" = TRUE;